name: Actualizar Mercato Diario

on:
  schedule:
    # Se ejecuta todos los días a las 05:00 UTC (puedes ajustarlo)
    - cron: '0 5 * * *'
  workflow_dispatch:
    # Permite ejecutarlo manualmente desde la pestaña "Actions" en GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Clonar el repositorio
        uses: actions/checkout@v3

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 3. Instalar dependencias
        run: npm install

      - name: 4. Crear archivo de credenciales desde el secreto
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
      
      - name: 5. Ejecutar el script de actualización
        run: node update-script.js
        
      - name: 6. Subir los cambios al repositorio (Opcional, pero recomendado)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '📈 [Auto] Actualización de datos del mercato'
          file_pattern: 'mercado.html'
          
      - name: 7. Sincronizar con el hosting vía FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          remote-dir: ${{ secrets.REMOTE_PATH }}
          # Descomenta la siguiente línea si quieres que se suban solo los archivos que han cambiado
          # state-name: .ftp-state.json
